package/skelcd-control-openSUSE.changes, package/skelcd-control-openSUSE.spec
Signed-off-by: Dinar Valeev <dvaleev@suse.com>
=> Fix repo-oss on tumbleweed powerpc

control/nonoss.xsl, package/skelcd-control-openSUSE.changes, package/skelcd-control-openSUSE.spec
Signed-off-by: Dinar Valeev <dvaleev@suse.com>
=> Parseout non-oss repo on Power

package/skelcd-control-openSUSE.spec
Signed-off-by: Dinar Valeev <dvaleev@suse.com>
=> Bump version

control/control.openSUSE.xml
Adapt the display manager dialog in controls.xml to this change
=> e17 pattern was renamed to enlightenment

package/skelcd-control-openSUSE.changes, package/skelcd-control-openSUSE.spec
Signed-off-by: Dinar Valeev <dvaleev@suse.com>
=> Adapt update-repo for ports

control/control.openSUSE.xml, package/skelcd-control-openSUSE.changes, package/skelcd-control-openSUSE.spec
Add the `inst_update_installer` client (like this PR for SLES: https://github.com/yast/skelcd-control-SLES/pull/56).
=> Add inst_update_installer client

control/control.openSUSE.xml, package/skelcd-control-openSUSE.changes, package/skelcd-control-openSUSE.spec
Fixes second part of [bsc#984656](https://bugzilla.suse.com/show_bug.cgi?id=984656).
=> Delay autoupgrade self update

control/control.openSUSE.xml, package/skelcd-control-openSUSE.changes, package/skelcd-control-openSUSE.spec
See conversation at
https://lists.opensuse.org/opensuse-factory/2016-07/msg00417.html
=> Use lightdm as displaymanager when installing LXDE

control/control.openSUSE.xml, package/skelcd-control-openSUSE.changes, package/skelcd-control-openSUSE.spec
Same as https://github.com/yast/skelcd-control-SLED/pull/48 but for openSUSE.
=> Move self-update to the beginning of the installation

control/control.openSUSE.xml, package/skelcd-control-openSUSE.changes, package/skelcd-control-openSUSE.spec
For consistency with other entries (boo#997232)
=> Add missing slash to debug/update/leap/42.2/oss

control/control.openSUSE.xml, package/skelcd-control-openSUSE.changes, package/skelcd-control-openSUSE.spec
See also https://github.com/yast/skelcd-control-SLED/pull/49
=> Removed reference to nolonger useful network client

control/control.openSUSE.xml, package/skelcd-control-openSUSE.changes, package/skelcd-control-openSUSE.spec
https://trello.com/c/JdvwBp5G/457-5-microos-12-sp2-move-default-subvolumes-to-control-file
Very much the same as yast/skelcd-control-SLES#75 except for .spec and .changes
=> Added subvolumes to control.xml (fate#321737)

package/skelcd-control-openSUSE.changes, package/skelcd-control-openSUSE.spec
=> Increase version beyond Leap 42.3.

Rakefile, control/control.openSUSE.xml, package/skelcd-control-openSUSE.changes, package/skelcd-control-openSUSE.spec
Starting Leap 42.3 version per https://progress.opensuse.org/issues/14918.
=> Start Leap 42.3 version.

.gitignore, .travis.sh, .travis.yml, Dockerfile, control/control.openSUSE.xml, package/skelcd-control-openSUSE.changes, package/skelcd-control-openSUSE.spec
just backport of changes done for TW also for Leap 42.3
=> Merge master changes

package/skelcd-control-openSUSE.changes
Just to please the bug number check...
=> Add a bug number reference to .changes

control/control.openSUSE.xml, package/skelcd-control-openSUSE.changes, package/skelcd-control-openSUSE.spec
This should be submitted together with
https://github.com/yast/yast-installation/pull/568
But also runs without it.
=> default patterns in custom roles

control/control.openSUSE.xml, package/skelcd-control-openSUSE.changes, package/skelcd-control-openSUSE.spec
https://bugzilla.suse.com/show_bug.cgi?id=1042482
=> Fixed role description

Rakefile, control/control.openSUSE.xml, package/skelcd-control-openSUSE.spec
I decide to merge fixes from leap 42.3 instead of cherry picking and revert commits that should not go to tumbleweed as easier solution to not forget any fix.
=> Reword master

control/control.openSUSE.xml, package/skelcd-control-openSUSE.changes, package/skelcd-control-openSUSE.spec
- Fixes https://bugzilla.suse.com/show_bug.cgi?id=1054198
- 42.3.99.11
=> Use HTTPS protocol for downloading the community repositories

control/control.openSUSE.xml, package/skelcd-control-openSUSE.changes, package/skelcd-control-openSUSE.spec
required for https://github.com/yast/yast-installation-control/pull/51
=> Adapt roles

control/control.openSUSE.xml, package/skelcd-control-openSUSE.changes
Also includes free trailing whitespace tidyup - you're welcome ;)
=> adjust subvolume list to have NoCOW /var instead of many subvolumes

control/control.openSUSE.xml
See also **Notes** in https://trello.com/c/x8tyrOFi.
=> - rewrite partitioning section to use new storage-ng setting

control/control.openSUSE.xml, package/skelcd-control-openSUSE.changes, package/skelcd-control-openSUSE.spec
Looks like we forgot Leap 15 when changing all of our product control.xml's for libstorage-ng
=> Rebase Leap 15 controlfile with recent SLE 15/libstorage-ng changes

control/control.openSUSE.xml, package/skelcd-control-openSUSE.changes, package/skelcd-control-openSUSE.spec
In order to unblock https://build.opensuse.org/request/show/571135
=> workaround boo#1078495 by making swap unconfigurable

POTFILES, control/control.openSUSE.xml, package/skelcd-control-openSUSE.changes, package/skelcd-control-openSUSE.spec
causes more problems than solved, needed urgently to allow /var changes to reach Leap 15
=> remove boo#1078495 workaround

control/control.openSUSE.xml, package/skelcd-control-openSUSE.changes, package/skelcd-control-openSUSE.spec
See https://github.com/yast/yast-installation-control/pull/62.
=> Btrfs read-only

control/control.openSUSE.xml, package/skelcd-control-openSUSE.changes, package/skelcd-control-openSUSE.spec
- The firewall proposals were unified and adapted to work with the new firewalld api, but the control file was only modified in SLES (see https://github.com/yast/skelcd-control-leanos/pull/18)
- Backported also changes added in #120 into Leap15
=> Unification of firewall proposals

control/control.openSUSE.xml, package/skelcd-control-openSUSE.changes, package/skelcd-control-openSUSE.spec
- The firewall proposals were unified and adapted to work with the new firewalld api but the control file was only modified in SLES (see https://github.com/yast/skelcd-control-leanos/pull/18). The changes were added into Leap15 in #123 and this PR will also add them into TW.
=> Unification of firewall proposals (TW)

control/control.openSUSE.xml, package/skelcd-control-openSUSE.changes, package/skelcd-control-openSUSE.spec
As discussed on https://lists.opensuse.org/opensuse-factory/2018-07/msg00040.html
Also have an equivalent submission for Tumbleweed, will link the PR in a comment
=> NM by default for desktop roles. Use SLE-15 style roles. bsc#1100417

Rakefile, control/control.openSUSE.xml, package/skelcd-control-openSUSE.changes, package/skelcd-control-openSUSE.spec
For Rakefile, I think someone need to set up it on OBS.
=> Update all 15.1 related part to 15.1

control/control.openSUSE.xml, package/skelcd-control-openSUSE.changes, package/skelcd-control-openSUSE.spec
After a few fixes, I cannot find more issues with it, so let's let the world test it.
=> Switch installation UI for openSUSE to sidebar (boo#1088785) 

control/control.openSUSE.xml, package/skelcd-control-openSUSE.changes, package/skelcd-control-openSUSE.spec
=> Remove /home fallback attributes

control/control.openSUSE.xml, package/skelcd-control-openSUSE.changes, package/skelcd-control-openSUSE.spec
=> Move licenses to /usr/share/licenses/product

control/control.openSUSE.xml, package/skelcd-control-openSUSE.changes, package/skelcd-control-openSUSE.spec
- Backport the #151 fix to the Leap 15.1 branch
- Tested manually
=> Online repos step in Leap 15.1

control/control.openSUSE.xml, package/skelcd-control-openSUSE.changes, package/skelcd-control-openSUSE.spec
=> make sure yast gets installed with all roles (boo#1130998)

package/skelcd-control-openSUSE.changes, package/skelcd-control-openSUSE.spec
Related to https://github.com/openSUSE/download.o.o/pull/25
=> Update link to https://download.opensuse.org/YaST/Repos/* for non-x86

control/control.openSUSE.xml, package/skelcd-control-openSUSE.changes, package/skelcd-control-openSUSE.spec
=> Add boot/writable subvolume for Transact. Server

package/skelcd-control-openSUSE.changes, package/skelcd-control-openSUSE.spec
=> Backport fixes for 15.2 for aarch64 (bsc#1120938)

control/control.openSUSE.xml, package/skelcd-control-openSUSE.changes, package/skelcd-control-openSUSE.spec
- https://bugzilla.suse.com/show_bug.cgi?id=1171423
- https://trello.com/c/BqWDHmp1
Remove obsolete `proposal_settings_editable` setting from control files.
=> remove obsolete proposal_settings_editable

control/control.openSUSE.xml, package/skelcd-control-openSUSE.changes, package/skelcd-control-openSUSE.spec
=> Require enhanced_base for serverro (poo#66105)

control/control.openSUSE.xml, package/skelcd-control-openSUSE.changes, package/skelcd-control-openSUSE.spec
=> Remove /tmp subvolume for transactional systems

control/control.openSUSE.xml, package/skelcd-control-openSUSE.changes, package/skelcd-control-openSUSE.spec
This submission is urgent, due to previous submissions breaking Factory. Please review and merge ASAP
=> Revert remove /tmp subvolume for transactional-server

control/control.openSUSE.xml, package/skelcd-control-openSUSE.changes, package/skelcd-control-openSUSE.spec
=> Server Role should install the new yast2_server pattern

control/control.openSUSE.xml
Fix wrong comment. Reason at https://github.com/yast/skelcd-control-openSUSE/pull/227#discussion_r583534726
=> Fix comment

control/control.openSUSE.xml, package/skelcd-control-openSUSE.changes, package/skelcd-control-openSUSE.spec
Use the new security proposal in the right order.
See https://github.com/yast/skelcd-control-openSUSE/pull/228/commits/b4fe2ed1b6fc78638a5fefbe90ae69122d5c033d and https://github.com/yast/skelcd-control-openSUSE/pull/231
=> [Leap 15.3] Use the new proposal security client

package/skelcd-control-openSUSE.changes
Added missing changelog for #236 which adds the update debug repo.
- https://bugzilla.suse.com/show_bug.cgi?id=1182915
=> Add changelog entry for #236

package/skelcd-control-openSUSE.changes, package/skelcd-control-openSUSE.spec
=> Fix path of repo for Leap 15.3 armv7

control/control.openSUSE.xml, package/skelcd-control-openSUSE.changes, package/skelcd-control-openSUSE.spec
=> Upgrade manual network activation (Leap 15.3)

package/skelcd-control-openSUSE.changes
See https://bugzilla.suse.com/show_bug.cgi?id=1185510
=> Add missing bugzilla reference in changelog

control/control.openSUSE.xml, package/skelcd-control-openSUSE.changes, package/skelcd-control-openSUSE.spec
trello: https://trello.com/c/HtBLfvR0/4499-ostumbleweed-p5-1180699-microos-defaults-to-using-the-suse-ntp-pool
bzilla: https://bugzilla.suse.com/show_bug.cgi?id=1180699
related https://github.com/yast/yast-installation-control/pull/105
=> Ntp servers

Rakefile
- Correctly submit to Leap 15.4
=> Rakefile - fixed submission target

package/skelcd-control-openSUSE.changes, package/skelcd-control-openSUSE.spec
=> Disable kdump for %arm - boo#1203888

package/skelcd-control-openSUSE.changes, package/skelcd-control-openSUSE.spec
=> Bump version for #256

package/skelcd-control-openSUSE.changes
- code-o-o is not accepted yet
=> Add jira changelog reference to openh264 change

package/skelcd-control-openSUSE.changes, package/skelcd-control-openSUSE.spec
- Fix up for the previous update
=> xsltproc tool is still needed for building on some architectures

package/skelcd-control-openSUSE.spec
Updated this PR to only keep the spec-cleaner updates.
=> Spec-cleaner updates

control/control.xml, package/skelcd-control-openSUSE.changes, package/skelcd-control-openSUSE.spec
grub2-bls will be our next preferred bootloader in our products. So, give it a try in TW......
=> Set grub2-bls as default bootloader

control/control.xml, package/skelcd-control-openSUSE.changes, package/skelcd-control-openSUSE.spec
=> Systemd_fde in partition proposal
