yast/skelcd-control-openSUSE

package/skelcd-control-openSUSE.spec

Tumbleweed for ARM is hosted under /ports/ tree similarly to PPC, so reuse the code also for ARM.

Setup Tumbleweed repositories correctly for ARM

---

control/control.openSUSE.xml
package/skelcd-control-openSUSE.changes

Use empty string as value for DISPLAYMANAGER for minimal+X11 and textmode
pattern, which on the system already results in chosing xdm as default DM.
This enables us to set displaymanager in %post of the appropriated DM package.

Use empty string as DM value for minimal+X11 and textmode (FATE#319432)

---

control/control.openSUSE.xml
package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

- bsc#947398
- See also new test for these settings at https://github.com/yast/yast-update/pull/50

openSUSE Leap 42.1 added to the list of products supported for upgrade by this product

---

control/control.openSUSE.xml

add server install into main selection
to give more visibility that openSUSE is not only for the Desktop
(note: this will probably need adaptions in openQA code and needles)
install size is 979MB on x86_64 (2015-10-02)
considerations:
This server pattern is not intended to be minimal, because it should be generally useful, which means we need to include things that will be used in some, but not all cases.
here is a (old) preview of how the result looks:

primary Server selection

---

control/control.openSUSE.xml
package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

- Added SSH keys import section to the proposal. See https://github.com/yast/yast-installation/pull/374
- Remove not longer necessary items from the `copy_to_system` section
- SSH host keys no longer necessary. See https://build.opensuse.org/request/show/396066
- Users database not longer necessary for user import. See https://build.opensuse.org/request/show/393918

Fate#319624

---

package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

- 13.2.29
Note: We need to add the debugger package via this skelcd-control package dependency, dependency in an YaST package would add it also in the installed system which we do not want by default.
Note2: The same change will follow in the SLES/SLED skelcd packages.

Include the Ruby debugger (byebug) in the inst-sys (FATE#318421)

---

control/control.openSUSE.xml

The name of KDE's desktop is Plasma. Xfce is also not written in all-caps.

Update desktop names

---

control/control.openSUSE.xml
package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

Remove some files from the inst-sys to have more free RAM on low memory systems.
This PR activates the cleaner (https://github.com/yast/yast-installation/pull/407) in the installation/upgrade workflow.
- Version updated to 42.2.0 (to match Leap 42.2, it seems we forgot to bump the minor since openSUSE 13.2...)
The cleaner is called at the initial stage when the inst-sys is running in memory:
- Initial installation
- Upgrade
- Autoinstallation
- Autoupgrade

Inst-sys clean up (bsc#974601)

---

control/control.openSUSE.xml
package/skelcd-control-openSUSE.changes

Version bump is not needed now because last update was rejected: https://ci.opensuse.org/job/yast-skelcd-control-openSUSE-openSUSE-42_2/5/
Currently we have a versions conflict with `master` that we need to discuss and address.

Move self-update client to the beginning

---

control/control.openSUSE.xml
package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

- Removed obsolete parts related to the Live CD installation, the `yast2-live-installer` package has been  dropped in Tumbleweed 
- Switch the versioning schema to `42.2.99.x` to not conflict with openSUSE-42.2 (`42.2.x`)
- The change is related to this PR: https://github.com/yast/yast-live-installer/pull/12

Drop live CD config

---

control/control.openSUSE.xml
package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

related pull request:
https://github.com/yast/yast-packager/pull/231
https://github.com/yast/yast-installation/pull/515
https://github.com/yast/yast-yast2/pull/538
Videos how it now behaves:
old version: 
new version - picking kde and when it is reported as too big, pick gnome
new version - custom patterns and online repos

add new desktop roles

---

.travis.sh
.travis.yml
Rakefile

This reverts commit 89f74dd0a42fe590767b0864cede1bef309f10c2 (from PR #71).
The rake check:syntax is also called at Jenkins, it does not work there and breaks the package submission.

Revert "Improve the Travis check"

---

control/control.openSUSE.xml
package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

Users will be required to click something to get desktop.
Follows up on "Adjusting desktop defaults to reflect project realities" thread on opensuse-factory mailing list (not archived yet).

Select no default desktop on the selection list

---

.gitignore
control/control.openSUSE.xml
package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

As part of the patterns cleanup the generic_server pattern was merged into the console pattern and removed.

Replace the generic_server pattern reference with console.

---

control/control.openSUSE.xml
package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

I have tested TW upgrade locally, this is what I found in the logs:
```
modules/Update.rb:250 Processing 'openSUSE Tumbleweed' from '/mnt'
modules/Update.rb:138 A regexp matches the installed product: false
clients/update_proposal.rb:468 Upgrade is not supported
```
- Added the new TW identification to the list of the products supported for upgrade  ([bsc#1039193](https://bugzilla.suse.com/show_bug.cgi?id=1039193))
- 42.3.99.5

Added the new TW identification (bsc#1039193)

---

control/control.openSUSE.xml
package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

yast2-live-installer package has been dropped in Tumbleweed, but it is still provided in openSUSE Leap and needs sections for Live installation

Re-add section for Live installation (boo#1042559)

---

package/skelcd-control-openSUSE.spec

The following line was trying to mv the _ports file back, so
we need to write it under the temporary name

Fix build error on non-x86

---

package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

supposed to solve error since
commit#c5e2b30ae60196059134db87e0c462b67d32618f
build error as per 
https://build.opensuse.org/package/live_build_log/openSUSE:Factory:PowerPC:Rings:1-MinimalX/skelcd-control-openSUSE/standard/ppc64le
```
[   59s] + xsltproc -o /home/abuild/rpmbuild/BUILDROOT/skelcd-control-openSUSE-42.3.99.18-3.1.ppc64le/CD1/control.xml control/nonoss.xsl /home/abuild/rpmbuild/BUILDROOT/skelcd-control-openSUSE-42.3.99.18-3.1.ppc64le/CD1/control.xml/
[   59s] warning: failed to load external entity "/home/abuild/rpmbuild/BUILDROOT/skelcd-control-openSUSE-42.3.99.18-3.1.ppc64le/CD1/control.xml/"
[   59s] unable to parse /home/abuild/rpmbuild/BUILDROOT/skelcd-control-openSUSE-42.3.99.18-3.1.ppc64le/CD1/control.xml/
[   59s] error: Bad exit status from /var/tmp/rpm-tmp.NnrXyD …
```

Change xsltproc parms in spec to avoid PowerPC build error

---

control/control.openSUSE.xml
package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

- [Trello Card](https://trello.com/c/eLMiRWmH/1350-2-bug-1078991-l3-autoyast-unable-to-find-disk-with-option-withfcoe)

Add 'fcoe-client' to the list of clonable modules

---

control/control.openSUSE.xml
package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

- Originally the idea was to merge openSUSE-15_0 branch, but taking in account the number of changes will add the commits separately.
- [Trello Card](https://trello.com/c/eLMiRWmH/1350-2-bug-1078991-l3-autoyast-unable-to-find-disk-with-option-withfcoe)

Add 'fcoe-client' to the list of clonable modules (TW)

---

control/control.openSUSE.xml
package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

This introduces the new "Server with Transactional Updates & Read Only Root Filesystem" system role for openSUSE Leap 15
This will let users set up an openSUSE Leap system similar to Tumbleweed-Kubic, but with a potentially broader range of use cases that Kubic's container focus (It's Leap after all ;))
This change will need changes to openQA to handle the new installation workflow, those are being prepared. It will be easier to coordinate staging and testing if we merge this with #121

Introduce Server-with-Transactional-Updates System Role (Leap 15)

---

control/control.openSUSE.xml
package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

This introduces the new "Server with Transactional Updates & Read Only Root Filesystem" system role for openSUSE Tumbleweed.
This will let users set up an openSUSE Tumbleweed system similar to Tumbleweed-Kubic, but with a potentially broader range of use cases that Kubic's container focus (It's Tumbleweed after all)
This change will need changes to openQA to handle the new installation workflow, those are being prepared. It will be easier to coordinate staging and testing if we merge this with it's Leap 15 companion PR, which will be linked to this one promptly.

Introduce Server-with-Transactional-Updates System Role

---

control/control.openSUSE.xml

The yast online repo module does not support such urls. So that would
lead to duplicate repos when using that module.
This reverts commit 34f38d19038986ed5335cd77f3ac9364955a6856.

Revert "Use $releasever in repo urls" (boo#1090193)

---

control/control.openSUSE.xml
package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

Removed after discussion in the openSUSE Release Engineering team - any common functionality hindered by the removal of this system role can be returned with the addition of new system roles in the future

Remove 'Custom' system_role (boo#1100417)

---

control/control.openSUSE.xml
package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

- https://bugzilla.suse.com/show_bug.cgi?id=1105335
- The list of regexps contained only "openSUSE Leap 42.x" product, the version 15.0 was not marked as supported.
- 42.3.99.31

Upgrade from openSUSE Leap 15.x is supported (bsc#1105335)

---

Rakefile

- Updated the `rake version:bump` task to work properly with the new versioning schema in master,
see #148 for the details.
- It uses just the current date if the old version is different, e.g. `20181110` => `20181113`
- If the package has been already released today it adds a release version starting with 1:  
`20181113` => `20181113.1`
- The next updates will increase the release version: `20181113.2`,  `20181113.3`, `20181113.4`, ...
- The next day (or anytime later) the version is updated and the release is removed:
`20181113.3` => `20181114`
- It uses the UTC date to avoid possible conflicts when running on the same day but in different time zones by different developers.

Updated "rake version:bump" task

---

control/control.openSUSE.xml
package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

https://trello.com/c/VgNO1EBi/442-ludwigs-favorite-feature-leap-151-add-possibility-to-add-online-updates-repo-during-installation
https://bugzilla.suse.com/show_bug.cgi?id=1112937
This adds the "online repos" step to the installation workflow.
This step was always there for the upgrade workflow; now it is also there for the installation.
The module itself takes care to skip itself to first ask if the user wishes to activate online repos. It also auto-skips itself if no network is configured; network configuration is done earlier in the workflow.
https://github.com/yast/yast-packager/pull/385
Demonstrated to and approved by @lnussel .

Added workflow step to add online repos during installation

---

control/control.openSUSE.xml
package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

Related to https://bugzilla.suse.com/show_bug.cgi?id=1115986
| After | Before |
|--------------|-----------------------|
| ![screenshot_opensuse_2018-11-14_14 15 40](https://user-images.githubusercontent.com/1691872/48836920-f1e6df80-ed7b-11e8-8d73-af14b900bd83.png) | ![screenshot from 2018-11-21 11-54-27](https://user-images.githubusercontent.com/1691872/48836887-d8de2e80-ed7b-11e8-93e1-a1988cddd485.png) |

Remove not necessary step names

---

.travis.sh

- This fixes Travis not failing when an error is found in the changes, see [this Travis build](https://travis-ci.org/yast/skelcd-control-openSUSE/builds/458436408#L393).
- The `source_validator` is fine when at least one changes file is correct, we need to be sure both are OK.

Explicitly check the changelog sequence

---

control/control.openSUSE.xml
package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

Displays Network Proposal in Installation Proposal
- https://fate.suse.com/326480
- https://trello.com/c/4ptXAFVW/441-network-proposal-in-leap-151-networkmanager
- https://trello.com/c/eBiqtDo7/706-2-bug-1124478-and-1124498-build-1584-switching-from-nm-to-wicked-and-back-and-forth
- ***The same as https://github.com/yast/skelcd-control-openSUSE/pull/169, but for TW***
---
- ***Related PR:* https://github.com/yast/yast-network/pull/727**

Add network to installation proposal overview page

---

control/control.openSUSE.xml
package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

After changes made for fate#324053 / jsc#SLE-4173, the license for the base product will be located at `/usr/share/licenses/product/base` instead of `/etc/YaST2/licenses/base`.
Related to #173 and #175.
Also discussed in https://github.com/yast/skelcd-control-Kubic/pull/31
---
More info available in fate#324053, jsc#SLE-3067, and jsc#SLE-4173

Update path for base product license

---

package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

%{_arch} macro is 'arm' instead of armv6hl and armv7hl

Fix %arm links

---

package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

Unlike all the other repositories, the ports updates are not
under /ports/$portsarch/ but under /ports/update (e.g. all
architectures under one directory). Special case this exception
for leap (it is "normal" for tumbleweed). The reason for
this is in how the opensuse maintenance engine works (it
can handle only one Update project for each arches) so it
cannot be changed easily.
Forward port to master to ensure this doesn't get lost
again when openSUSE Leap 15.1 or 16 gets branched.

Adjust update repo for ports

---

control/control.openSUSE.xml
package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

In the past, yast silently ignored this setting and went for wicked
if NetworkManager did not get installed. Since yast2-network 4.1.40,
this is no longer the case: if the role asked for NetworkManager,
yast now selects NM for installation to comply to he request.
The generic desktop role is a minimal X environment, where no
NetworkManager applet is pre-installed by default. So staying with
wicked, as it used to be by accident, is what we want not by definition.

Default to wicked on generic desktop role

---

.github/pull_request_template.md

The issue #179 was very likely caused just by fixing the #151 problem only in the `master` branch.
But at that time the Leap 15.1 was already branched (in contrast to the other YaST packages) so it was easy to overlook the fact that the change should have been also backported to the `openSUSE-15_1` branch.
Having a reminder in the pull request template should hopefully avoid this issue.

Added a pull request reminder

---

control/control.openSUSE.xml
package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

Having a system role for Xfce in the installer has two main advantages:
1) The Xfce desktop is already included in the DVD media, it would make sense to have it as on option to select from the start. Although not as popular as KDE and GNOME, Xfce has a fair amount of users in the openSUSE community.
2) As I'm  creating Live XFCE media , this step would make the installer in the live cd easier to set up. The current setup forces the user to go through the "generic desktop", an extra step that is not intuitive for the average user.

Add Xfce system role

---

control/control.openSUSE.xml
package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

Follow up to PR #182 :
- added `x11_yast` and `yast2_basis` to Xfce system role 
- cleaned white spaces

Make sure YaST is installed with Xfce system role too in Tumbleweed

---

control/control.openSUSE.xml
package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

Replacement for https://github.com/yast/skelcd-control-openSUSE/pull/189 I had to send it through another branch
Generic desktop requires basic_desktop pattern 
gnome, kde and xfce system roles now pull in the enhanced base pattern as well because they used to do that

Generic desktop requires basic_desktop pattern + other fix

---

control/control.openSUSE.xml
package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

Yast was modified for Kubic to have a selector for the base product. This is needed, as in TW's FTP tree, we have MicroOS and openSUSE side-by-side.
So far, this was not needed, as openSUSE was the only product with system_installation defined. For Kubic to have MicroOS as selectable base product, it must provide the symbol as well. This means, that the FTP tree now would have two base products, resulting in the Installer asking for which one to install. Ads we don't want that on the TW NETISO and DVD, we are now preselecting the right product

Mark openSUSE as the preferred base product

---

Rakefile
package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

- Adapt the `Rakefile` to submit to Leap 15.2
- Bump the version to 15.0.x

Adapt for the openSUSE Leap 15.2 release (bsc#1141654)

---

control/control.openSUSE.xml
package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

#138 added the `/boot/grub2/arm64-efi` subvolumes but only for the `transactional server` role.
This PR adds this subvolume to the default list, so it is applied to all roles.
A PR to the master branch will follow after this one is approved.
See [bsc#1162320](https://bugzilla.suse.com/show_bug.cgi?id=1162320) for further information.

Add /boot/grub2/arm64-efi subvolume for all roles

---

control/control.openSUSE.xml
package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

#138 added the `/boot/grub2/arm64-efi` subvolumes but only for the `transactional server` role.
This PR adds this subvolume to the default list, so it is applied to all roles.
See the #197 for the Leap 15.2 counterpart or [bsc#1162320](https://bugzilla.suse.com/show_bug.cgi?id=1162320) for further information.

 Add /boot/grub2/arm64-efi subvolume for all roles (TW)

---

control/control.openSUSE.xml
package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

#138 added the `/boot/grub2/arm64-efi` subvolumes but only for the `transactional server` role.
This PR adds this subvolume to the default list, so it is applied to all roles.
See the #197 for the Leap 15.2 counterpart or [bsc#1162320](https://bugzilla.suse.com/show_bug.cgi?id=1162320) for further information.

Add /boot/grub2/arm64-efi subvolume for all roles (Leap 15.1)

---

package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

This PR should fix https://bugzilla.opensuse.org/show_bug.cgi?id=1120938
Backport to `openSUSE-15_2` branch will follow.

Update external link for non-x86 on Leap - bsc#1120938

---

package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

At the moment the repositories added are for x86_64.

Fix repo URL for s390x

---

package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

*yast2-installation* does not recommend *release-notes* package anymore, see https://github.com/yast/yast-installation/pull/845. As a consequence,  release notes are not included in the installation media.
* https://bugzilla.suse.com/show_bug.cgi?id=1167866
A dependency of *release-notes* package has been added to skelcd-control-openSUSE. Now, release notes would be available in the installation media but it would not be installed when *yast2-installation* is needed on the running system.

Add release notes dependency

---

control/control.openSUSE.xml
package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

During the upgrade mode, the option for configuring network is not offered. This option is specially useful to configure WIFI in laptops without a ethernet port.
* https://bugzilla.suse.com/show_bug.cgi?id=1173676
Add missing step to update mode.

Add Network Activation to update mode

---

control/control.openSUSE.xml
package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

Removed unneeded AY installation step "autoimage" (bsc#1140711).

---

control/control.openSUSE.xml
package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

Changes to systemd and microos-tools are now on the way so this change is now safe/expected for everyone.
https://bugzilla.suse.com/show_bug.cgi?id=1173461

Remove /tmp subvolume

---

package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

Fixes https://github.com/yast/skelcd-control-openSUSE/pull/203 by backporting https://github.com/yast/skelcd-control-openSUSE/pull/215

Backport fix for 15.2 for aarch64 (bsc#1120938)

---

control/control.openSUSE.xml
package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

It is a backport from 
https://github.com/yast/skelcd-control-openSUSE/pull/218

Upgrade openSUSE->Jump. Allow vendor change without asking the user.

---

package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

This fixes https://github.com/yast/skelcd-control-openSUSE/pull/201

Fix update external link for non-x86 on Leap - bsc#1120938

---

control/control.openSUSE.xml
package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

During an autoinstallation, if the networking section only contains the [keep_install_network](https://doc.opensuse.org/projects/autoyast/#CreateProfile-Network) option it should copy the network configuration from linuxrc to the target system. This is not the case of the hostname option which is lost.
- https://bugzilla.suse.com/show_bug.cgi?id=1177768
Add the install_inf client to be run also in autoinstallation (see https://github.com/yast/yast-installation/pull/893)

AY: write linuxrc proxy and hostname to inst-sys

---

package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

as all supported archs are built in the same project and published in the same online directory.

Do not update repo paths for Leap 15.3 and later

---

control/control.openSUSE.xml

* support xfce boo#1178497
* drop autoimage boo#1181790

Leap 15.3 setup

---

Rakefile
package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

- Make it similar to https://github.com/yast/skelcd-control-openSUSE/blob/openSUSE-15_2/Rakefile
- Use 15.3.x versioning

Fix Rakefile for Leap 15.3

---

control/control.openSUSE.xml
package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

Related to feature https://jira.suse.com/browse/SLE-17307 (internal link), sets SELinux as a major [**L**inux **S**ecurity **M**odule](https://www.kernel.org/doc/html/latest/admin-guide/LSM/index.html) in its permissive mode, as requested at https://github.com/yast/yast-installation/pull/906#issuecomment-784238549.
For openSUSE Leap, see https://github.com/yast/skelcd-control-openSUSE/pull/227
--- 
Related to https://github.com/yast/yast-security/pull/87 and https://github.com/yast/yast-installation/pull/906

[Tumbleweed] Set SELinux permissive mode by default

---

control/control.openSUSE.xml
package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

Related to feature https://jira.suse.com/browse/SLE-17307 (internal link), sets SELinux as a major [**L**inux **S**ecurity **M**odule](https://www.kernel.org/doc/html/latest/admin-guide/LSM/index.html) in its ~~permissive~~ **disabled** mode in spite of the requested at https://github.com/yast/yast-installation/pull/906#issuecomment-784238549  (see https://github.com/yast/skelcd-control-openSUSE/pull/227#discussion_r583534726) .
For openSUSE Tumbleweed, see https://github.com/yast/skelcd-control-openSUSE/pull/228
--- 
Related to https://github.com/yast/yast-security/pull/87 and https://github.com/yast/yast-installation/pull/906

[Leap 15.3] Set SELinux permissive mode by default

---

control/control.openSUSE.xml
package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

bsc: https://bugzilla.suse.com/show_bug.cgi?id=1183583
basically selinux is not ready to be enabled by default and also it changes behavior as it by default disable apparmor.

Selinux change

---

control/control.openSUSE.xml
package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

bsc: https://bugzilla.suse.com/show_bug.cgi?id=1183804
Issue is that security module adds selinux pattern if selinux is enabled, but it is after software proposal is computed. So it is shown only after recompute of proposal that does not need to happen. So move security upper.

Fix security proposal

---

package/skelcd-control-openSUSE.changes

This is a fixup for https://github.com/yast/skelcd-control-openSUSE/pull/233

Add bug number for previous commit

---

control/control.openSUSE.xml
package/skelcd-control-openSUSE.spec

* supply update-debug repository

Fix boo#1182915 - add repo-debug-update to Leap 15.3

---

package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

Port of https://github.com/yast/skelcd-control-openSUSE/pull/238 for Leap 15.4 branch

Fix path of repo for Leap 15.3+ armv7 (boo#1183795)

---

package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

Forward port of https://github.com/yast/skelcd-control-openSUSE/pull/238

Fix path of repo for Leap 15.3 armv7

---

control/control.openSUSE.xml
package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

In openSUSE, the manual network configuration is not part of the upgrade workflow which means that in case of no network it is tricky to setup it during the upgrade.
- https://bugzilla.suse.com/show_bug.cgi?id=1188689
Add the network client as it is already for [SLES/SLED](https://github.com/yast/skelcd-control-leanos/blob/master/control/control.leanos.xml#L643)

Upgrade manual network activation

---

Rakefile

Submit openSUSE 15.3 changes to `openSUSE:Leap:15.3:Update`.
Already submitted manually by https://build.opensuse.org/request/show/908856

Update Rakefile for Leap15.3 updates

---

control/control.openSUSE.xml
package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

Similar to https://github.com/yast/skelcd-control-openSUSE/pull/223 but for Leap 15.3

Define default NTP servers for Leap (bsc#1180699)

---

control/control.openSUSE.xml
package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

While respining Leap 15.3 we should fix this issue in skelcd-control and removing the workaround from the release package bsc#1186593 . Please do not submit this to `openSUSE:Leap:15.3:Updat`e, this should be stricts to Leap 15.3 respin only, `:Update` project should not accept/publish any skelcd-control change though.

Add backports-update, backports-debug-update, sle-update and sle-debug-update to control file

---

control/control.openSUSE.xml
package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

For more info, see https://github.com/yast/yast-security/pull/115 and https://github.com/yast/yast-installation/pull/1006
---

Added new 'lsm' section for selecting the desired Linux Security Module during installation

---

control/control.openSUSE.xml
package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

Wicked lacks caretaking in Tumbleweed and is just slow to boot.
NetworkManager is good enough also for most common server use cases
in Tumbleweed so let's just use one technology for all roles.
YaST anyway allows to switch to wicked in the proposal screen. So those
who know that they need for advanced cases wicked can still have it.

Use NetworkManager always

---

package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

- Related to https://github.com/yast/yast-kdump/pull/128, `yast2-kdump` now uses a runtime dependency
- But we also need the `kdump` package in the inst-sys ([bsc#875765#c4](https://bugzilla.suse.com/show_bug.cgi?id=875765#c4))
- So add it explicitly here

Added "kdump" dependency

---

control/control.openSUSE.xml

After I came across several opinions that the default installation is "overloaded", I think it is necessary to change the name and description of the graphical system roles.
- first of all, these sets are really **complete**.
- for a beginner who does not want to install something after installation, but wants to "_just work_", these changes will only emphasize his choice.
- for more experienced who do not want an "_overloaded_" desktop, this change will allow his to pay attention to the "Generic Desktop" item and make it clear that he can either from scratch set up your environment, or select the full set and remove the unnecessary ones from there. He may still not notice the ability to configure a set of packages before installation, however, this change will give him an understanding …

more accurate name and description of graphical system roles

---

package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

The i586 repos are already available on download.o.o:
https://download.opensuse.org/ports/i586/tumbleweed/
Even though i586 currently still exists in openSUSE:Factory (and produces an image) I think we can already set the new URLs as default for all i586 new installers (if there are any)

Define i586 as an external port

---

package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

LegacyX86: unlike other ports, i586 does have a valid non-oss
repo. Do not filter it out (related to boo#1206406).

LegacyX86 port: enable non-oss repository

---

control/control.openSUSE.xml

- We have now a redistribution agreement with Cisco https://en.opensuse.org/OpenH264#Installation
- Original request https://code.opensuse.org/leap/features/issue/22

Enable openh264 repo by default on Leap 15.4

---

control/control.openSUSE.xml
package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

* We have now a redistribution agreement with Cisco https://en.opensuse.org/OpenH264#Installation
* Original request https://code.opensuse.org/leap/features/issue/22

Enable openh264 by default on Tumbleweed

---

package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

Supply missing openh264 changelog entry for 15.4
Resolves jsc#OPENSUSE-46 jsc#SLE-18915

openh264: bump for 15.4

---

control/control.openSUSE.xml
package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

Remove from TW no longer used proposals definition. It contain also sound proposal and yast2-sound is going to drop. BTW in network proposal there was also some already dropped clients.

Drop sound

---

control/control.openSUSE.xml
package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

- Use http:// for openh264 as the redirectiont target
does not support https:// (Resolves boo#1207567).
- Bump external sources and migrate-to to 15.4

Leap 15.4: use http for openh264 and bump to 15.4

---

package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

- Fix up for the previous update
- Fixes build on ARM: https://build.opensuse.org/package/live_build_log/YaST:Head/skelcd-control-openSUSE/openSUSE_Factory/aarch64

xsltproc tool is still needed for building on some architectures

---

control/control.openSUSE.xml
package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

- It turned out that the package was patched directly in OBS and without changing the code in Git
- See https://build.opensuse.org/package/view_file/openSUSE:Leap:15.5/skelcd-control-openSUSE/fix_openh264_format.patch?expand=1
- Include the fix directly in the Git repository
- 15.5.4

Imported the fix by Yuchen Lin from OBS to Git

---

package/skelcd-control-openSUSE.changes

- The SR for the previous patch was declined because it does not mention removal of the `fix_openh264_format.patch` in the changes
- See https://build.opensuse.org/request/show/1086785
- See the previous PR #277

Updating the change log

---

Rakefile
control/control.openSUSE.xml
package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

https://bugzilla.suse.com/show_bug.cgi?id=1215432
https://trello.com/c/8SW384Bo/
No specific control file for Leap 15.6 yet.
- Created a new branch _openSUSE-15_6_ based on _openSUSE-15_5_.
- Adapted the toplevel _Rakefile_ to use the _openSUSE:Leap:15.6_ OBS target.
- Adapted the control.xml file to the new distro release.

Adapted to Leap 15.6

---

control/control.xml
package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

Back at 2018, a pull request was merged to (among other things) start using the YaST client `system_role` instead of the previous client `desktop_role`. #139.
That pull request [removed the label for the installation step](https://github.com/yast/skelcd-control-openSUSE/commit/527120f487ba01fb9c7cb89c27fc5a75f9a9e23b#diff-6fd657077cfb5e0ff393b2a9cc86746e10cf5baa24abbf8c3a48e4ed7cb7030cL1015). I doubt that was intentional.
This reintroduces the label, hopefully fixing [bsc#1228171](https://bugzilla.suse.com/show_bug.cgi?id=1228171).

Restore label for system roles

---

control/control.xml
package/skelcd-control-openSUSE.changes
package/skelcd-control-openSUSE.spec

as discussed with @DimStar77 we want to change the default LSM in tumbleweed to selinux in enforcing mode
see also email "RFC: SELinux as default MAC system on new Tumbleweed installations"
Tested using tumbleweed live iso and copying the control.xml into /etc/YaST2/control.xml and installing the system via installer
Please let me know if something is missing or you would like me to do additional testing

Select SELinux as default MAC in enforcing mode
